<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Фотограф | Твое Имя</title>
    <style>
        /* Общие стили */
        body {
            margin: 0;
            font-family: 'Arial', sans-serif;
            background-color: #1e1e1e;
            color: #f5f5f5;
            text-align: center;
        }
        
        /* Анимация появления */
        .fade-in {
            opacity: 0;
            transform: translateY(20px);
            animation: fadeIn 1s ease-out forwards;
        }
        
        @keyframes fadeIn {
            from {
                opacity: 0;
                transform: translateY(20px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }
        
        /* Навигация */
        nav {
            padding: 20px;
            background: rgba(0, 0, 0, 0.5);
            position: fixed;
            width: 100%;
            top: 0;
            left: 0;
        }
        nav a {
            color: #f5f5f5;
            text-decoration: none;
            margin: 0 15px;
            font-size: 18px;
            transition: 0.3s;
        }
        nav a:hover {
            color: #ffcc00;
        }
        
        /* Главный блок */
        .hero {
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            background: url('https://source.unsplash.com/1600x900/?photography') no-repeat center/cover;
        }
        .hero h1 {
            font-size: 50px;
            font-weight: bold;
            text-shadow: 2px 2px 10px rgba(0, 0, 0, 0.7);
        }
        .hero p {
            font-size: 20px;
            margin-top: 10px;
        }

        /* Галерея */
        .gallery {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 10px;
            padding: 50px;
        }
        .gallery img {
            width: 100%;
            border-radius: 5px;
            transition: transform 0.3s ease;
        }
        .gallery img:hover {
            transform: scale(1.05);
        }

        /* Форма обратной связи */
        .contact {
            padding: 50px;
            background-color: #282828;
        }
        .contact h2 {
            margin-bottom: 20px;
        }
        form {
            display: flex;
            flex-direction: column;
            max-width: 400px;
            margin: auto;
        }
        input, textarea {
            padding: 10px;
            margin-bottom: 10px;
            border: none;
            border-radius: 5px;
            background: #3a3a3a;
            color: white;
        }
        button {
            padding: 10px;
            border: none;
            background: #ffcc00;
            color: #1e1e1e;
            font-weight: bold;
            cursor: pointer;
            transition: 0.3s;
        }
        button:hover {
            background: #e6b800;
        }

        /* Подвал */
        footer {
            padding: 20px;
            background: #111;
            color: #777;
            font-size: 14px;
        }
    </style>
</head>
<body>

    <nav class="fade-in">
        <a href="#gallery">Галерея</a>
        <a href="#contact">Контакты</a>
    </nav>

    <div class="hero fade-in">
        <h1>Daria Davidov</h1>
        <p>Фотограф | Искусство света и тени</p>
    </div>

    <section id="gallery" class="gallery fade-in">
        <img src="https://source.unsplash.com/600x400/?portrait" alt="Фото 1">
        <img src="https://source.unsplash.com/600x400/?landscape" alt="Фото 2">
        <img src="https://source.unsplash.com/600x400/?city" alt="Фото 3">
        <img src="https://source.unsplash.com/600x400/?blackandwhite" alt="Фото 4">
    </section>

    <section id="contact" class="contact fade-in">
        <h2>Свяжитесь со мной</h2>
        <form>
        <input type="text" placeholder="Ваше имя" required>
            <input type="email" placeholder="Ваш email" required>
            <textarea placeholder="Ваше сообщение" rows="4" required></textarea>
            <button type="submit">Отправить</button>
        </form>
    </section>

    <footer>
        © 2025 Твое Имя. Все права защищены.
    </footer>

</body>
</html>
